global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "airflow-webserver"
    metrics_path: /admin/metrics
    static_configs:
      - targets: ["airflow-webserver:8080"]

  - job_name: "fastapi-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8000"]

  - job_name: "streamlit-webapp"
    metrics_path: /metrics
    static_configs:
      - targets: ["webapp:9100"]
